#!/usr/bin/env bash

docker build \
    --no-cache \
    -t ghcr.io/radical-egg/vein-dedicated-server:latest .

docker build \
    --no-cache \
    -f backup.Dockerfile \
    -t ghcr.io/radical-egg/vein-dedicated-backup:latest .
